[package]
name = "surreal-rust-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.160"
surrealdb = "1.0.0-beta.9"
tokio = { version = "1.27.0", features = ["full"] }
